name: Generate snake animation

on:
  schedule:
    # executa a cada 12 horas, no minuto 0
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg?palette=github-dark
            dist/snake-light.svg?palette=github-light

      - name: Commit and push SVGs
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/*.svg"
          message: "chore: update snake.svg"
          push: true

          <h2 align="left">Hi 👋! My name is ... and I'm a ..., from ....</h2>

<div align="center">
  <img src="https://github-readme-stats.vercel.app/api?username=SEU_USUARIO&hide_title=false&hide_rank=false&show_icons=true&include_all_commits=true&count_private=true&disable_animations=false&theme=dracula&locale=pt-br&hide_border=false" height="150" alt="stats graph"  />
  <img src="https://github-readme-stats.vercel.app/api/top-langs?username=SEU_USUARIO&locale=pt-br&hide_title=false&layout=compact&card_width=320&langs_count=5&theme=dracula&hide_border=false" height="150" alt="languages graph"  />
</div>

<img align="right" height="150" src="https://i.imgflip.com/65efzo.gif"  />

<!-- seus ícones/selos... -->

<br clear="both" />

<!-- Mostra a cobra; usa <picture> pra alternar tema -->
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="./dist/snake.svg" />
  <source media="(prefers-color-scheme: light)" srcset="./dist/snake-light.svg" />
  <img alt="Snake animation" src="./dist/snake.svg" />
</picture>
